In [1]:
import pandas as pd

In [2]:
df_war_and_peace = pd.read_csv("data/guerre_et_paix.csv")

In [3]:
df_war_and_peace

,Unnamed: 0,tome,chapitre,section,id,count,gender,number,mentions,agent,...,existence_state,human_relations,motion,not_a_valid_character_attribute,perception,personality_traits,physical_objects,physical_traits,possession,sociological
0,0,TOME_I,CHAPITRE_PREMIER,I,0,"{'occurrence': 131, 'mention_ratio': 0.3754}","{'ratio': 0.374, 'inference': {'Male': 0.88, '...","{'ratio': 0.7252000000000001, 'inference': {'S...","{'proper': [{'n': 'au prince basile', 'c': 1},...","[{'w': 'cesser', 'i': 34}, {'w': 'dire', 'i': ...",...,2,4,6,9,4,6,1,0,0,7
1,1,TOME_I,CHAPITRE_PREMIER,I,1,"{'occurrence': 35, 'mention_ratio': 0.1003}","{'ratio': 0.4857, 'inference': {'Male': 0.24, ...","{'ratio': 0.8857, 'inference': {'Singular': 1....","{'proper': [{'n': 'anna pavlovna schérer', 'c'...","[{'w': 'dire', 'i': 9}, {'w': 'déclarer', 'i':...",...,4,6,1,2,0,2,0,0,0,4
2,2,TOME_I,CHAPITRE_PREMIER,I,2,"{'occurrence': 33, 'mention_ratio': 0.0946}","{'ratio': 0.2121, 'inference': {'Male': 0.5700...","{'ratio': 0.7879, 'inference': {'Singular': 1....","{'proper': [{'n': 'anna pavlovna', 'c': 1}], '...","[{'w': 'croire', 'i': 897}, {'w': 'tenir', 'i'...",...,0,1,2,1,2,0,0,0,0,0
3,3,TOME_I,CHAPITRE_PREMIER,I,3,"{'occurrence': 15, 'mention_ratio': 0.04300000...","{'ratio': 0.2, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 0.8667, 'inference': {'Singular': 1....","{'proper': [{'n': 'le prince basile', 'c': 1},...","[{'w': 'dire', 'i': 2128}, {'w': 'indiquer', '...",...,0,2,0,0,0,0,0,0,1,0
4,4,TOME_I,CHAPITRE_PREMIER,I,4,"{'occurrence': 12, 'mention_ratio': 0.0344}","{'ratio': 0.5, 'inference': {'Male': 0.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'anna pavlovna', 'c': 1}], '...","[{'w': 'continuer', 'i': 1638}, {'w': 'rapproc...",...,0,0,2,1,2,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7869,7869,TOME_III,CHAPITRE_VI,VI,100,"{'occurrence': 2, 'mention_ratio': 0.0019}","{'ratio': 1.0, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'pierre', 'c': 1}], 'common'...",[],...,0,0,0,0,0,0,0,0,0,0
7870,7870,TOME_III,CHAPITRE_VI,VI,101,"{'occurrence': 2, 'mention_ratio': 0.0019}","{'ratio': 0.5, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 0.5, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'pierre', 'c': 1}], 'common'...","[{'w': 'parler', 'i': 5608}]",...,0,0,0,0,0,0,0,0,0,0
7871,7871,TOME_III,CHAPITRE_VI,VI,102,"{'occurrence': 2, 'mention_ratio': 0.0019}","{'ratio': 0.5, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'pierre', 'c': 1}], 'common'...","[{'w': 'revenir', 'i': 5761}]",...,0,0,0,0,0,0,0,0,0,0
7872,7872,TOME_III,CHAPITRE_VI,VI,103,"{'occurrence': 2, 'mention_ratio': 0.0019}","{'ratio': 0.5, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 0.5, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'dessalles', 'c': 1}], 'comm...","[{'w': 'demander', 'i': 6545}]",...,0,0,0,0,0,0,0,0,0,0
7873,7873,TOME_III,CHAPITRE_VI,VI,104,"{'occurrence': 2, 'mention_ratio': 0.0019}","{'ratio': 0.5, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'm. thiers', 'c': 1}], 'comm...","[{'w': 'applique', 'i': 6925}]",...,0,0,0,0,0,0,0,0,0,0

In [4]:
df_les_miserables = pd.read_csv("data/les_miserables.csv")

In [5]:
df_les_miserables

,Unnamed: 0,volume,livre,chapitre,id,count,gender,number,mentions,agent,...,existence_state,human_relations,motion,not_a_valid_character_attribute,perception,personality_traits,physical_objects,physical_traits,possession,sociological
0,0,hugo_les_miserables_cosette,Livre_premier_Waterloo,Chapitre_I_Ce_quon_rencontre_en_venant_d,0.0,"{'occurrence': 23, 'mention_ratio': 0.7931}","{'ratio': 0.7826000000000001, 'inference': {'M...","{'ratio': 0.8696, 'inference': {'Singular': 1....","{'proper': [], 'common': [{'n': 'le passant', ...","[{'w': 'raconter', 'i': 30}, {'w': 'arriver', ...",...,1,0,9,1,7,0,0,0,0,0
1,1,hugo_les_miserables_cosette,Livre_premier_Waterloo,Chapitre_I_Ce_quon_rencontre_en_venant_d,1.0,"{'occurrence': 5, 'mention_ratio': 0.1724}","{'ratio': 1.0, 'inference': {'Male': 0.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [], 'common': [{'n': 'une paysanne'...","[{'w': 'sortir', 'i': 606}, {'w': 'voir', 'i':...",...,0,0,1,0,2,0,0,0,0,0
2,2,hugo_les_miserables_cosette,Livre_premier_Waterloo,Chapitre_I_Ce_quon_rencontre_en_venant_de_Nive...,0.0,"{'occurrence': 23, 'mention_ratio': 0.7931}","{'ratio': 0.7826000000000001, 'inference': {'M...","{'ratio': 0.8696, 'inference': {'Singular': 1....","{'proper': [], 'common': [{'n': 'le passant', ...","[{'w': 'raconter', 'i': 30}, {'w': 'arriver', ...",...,1,0,9,1,7,0,0,0,0,0
3,3,hugo_les_miserables_cosette,Livre_premier_Waterloo,Chapitre_I_Ce_quon_rencontre_en_venant_de_Nive...,1.0,"{'occurrence': 5, 'mention_ratio': 0.1724}","{'ratio': 1.0, 'inference': {'Male': 0.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [], 'common': [{'n': 'une paysanne'...","[{'w': 'sortir', 'i': 606}, {'w': 'voir', 'i':...",...,0,0,1,0,2,0,0,0,0,0
4,4,hugo_les_miserables_cosette,Livre_premier_Waterloo,Chapitre_II_Hougomont,0.0,"{'occurrence': 15, 'mention_ratio': 0.121}","{'ratio': 0.4, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 0.7333000000000001, 'inference': {'S...","{'proper': [{'n': 'le sous-lieutenant legros',...","[{'w': 'tenir', 'i': 1406}, {'w': 'tirer', 'i'...",...,1,2,1,2,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5458,5458,hugo_les_miserables_marius,Livre_huitieme_Le_mauvais_pauvre,Chapitre_XXI_On_devrait_toujours_commenc,28.0,"{'occurrence': 2, 'mention_ratio': 0.0095}","{'ratio': 0, 'inference': {'Male': 0, 'Female'...","{'ratio': 0.5, 'inference': {'Singular': 1.0, ...","{'proper': [], 'common': [{'n': 'l’ homme à la...",[],...,0,0,0,0,0,0,0,0,0,0
5459,5459,hugo_les_miserables_marius,Livre_huitieme_Le_mauvais_pauvre,Chapitre_XXI_On_devrait_toujours_commenc,29.0,"{'occurrence': 2, 'mention_ratio': 0.0095}","{'ratio': 0, 'inference': {'Male': 0, 'Female'...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'javert', 'c': 1}], 'common'...",[],...,0,0,0,0,0,0,0,0,0,0
5460,5460,hugo_les_miserables_marius,Livre_huitieme_Le_mauvais_pauvre,Chapitre_XXII_Le_petit_qui_criait_au_tom,0.0,"{'occurrence': 42, 'mention_ratio': 0.5915}","{'ratio': 0.4048, 'inference': {'Male': 1.0, '...","{'ratio': 0.8571000000000001, 'inference': {'S...","{'proper': [{'n': 'mame burgon', 'c': 1}], 'co...","[{'w': 'crier', 'i': 6}, {'w': 'sembler', 'i':...",...,0,2,7,3,7,0,1,2,0,0
5461,5461,hugo_les_miserables_marius,Livre_huitieme_Le_mauvais_pauvre,Chapitre_XXII_Le_petit_qui_criait_au_tom,1.0,"{'occurrence': 23, 'mention_ratio': 0.3239}","{'ratio': 0.6087, 'inference': {'Male': 0.0, '...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [], 'common': [{'n': 'la vieille', ...","[{'w': 'fouiller', 'i': 104}, {'w': 'redresser...",...,0,2,3,1,5,0,0,0,0,1
5462,5462,hugo_les_miserables_marius,Livre_huitieme_Le_mauvais_pauvre,Chapitre_XXII_Le_petit_qui_criait_au_tom,2.0,"{'occurrence': 2, 'mention_ratio': 0.028200000...","{'ratio': 0.5, 'inference': {'Male': 1.0, 'Fem...","{'ratio': 1.0, 'inference': {'Singular': 1.0, ...","{'proper': [{'n': 'le roi coupdesabot', 'c': 1...","[{'w': 'aller', 'i': 747}]",...,0,0,1,0,0,0,0,0,0,0